[build-system]
requires = ["setuptools>=41", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.pylint]
max-line-length = 120
disable = ["missing-module-docstring"]


[tool.flake8]
max-line-length = 120
